---
bw: 12
bw_factor: 1
rtt: 20
bdp_mult: 2
num_steps: 1000
num_fields_kernel: 14
zeta: 5
kappa: 2
step_wait: 0.5
pool_size: 4
lr: 0.0001
mpts_T: 100
mpts_step_wait: 0.5
steps_per_loop: 1
seq_length: 5
server_ip: 10.172.13.12
server_port: 5201
iperf_time: 86400
log_mahimahi: true

kernel_info:
  - now
  - cwnd
  - rtt
  - srtt
  - rtt_dev
  - rtt_min
  - mss
  - delivered
  - lost
  - in_flight
  - retransmitted
  - delivery_rate
  - prev_proto_id
  - crt_proto_id
  - thruput
  - loss_rate

train_stat_features:
  - srtt
  - rtt_dev
  - lost
  - in_flight
  - thruput

train_non_stat_features:
  - cwnd
  - rtt
  - srtt
  - rtt_dev
  - lost
  - in_flight
  - delivery_rate
  - crt_proto_id
  - thruput
  - loss_rate

window_sizes:
  - 10
  - 200
  - 1000

protocols:
  cubic: 0
  hybla: 1
  bbr: 2
  westwood: 3
  veno: 4
  vegas: 5
  yeah: 6
  bic: 7
  htcp: 8
  highspeed: 9
  illinois: 10