models:
  adaptive_greedy_threshold:
    name: 'adaptive_greedy_threshold'
    marker: '*'
  adaptive_greedy_percentile:
    name: 'adaptive_greedy_percentile'
    marker: 'h'
  adaptive_greedy_weighted:
    name: 'adaptive_greedy_weighted'
    marker: '^'
  bootstrapped_ts:
    name: 'bootstrapped_ts'
    marker: '<'
  bootstrapped_ucb:
    name: 'bootstrapped_ucb'
    marker: '>'
  epsilon_greedy_decay:
    name: 'epsilon_greedy_decay'
    marker: 'H'
  epsilon_greedy:
    name: 'epsilon_greedy'
    marker: 'p'
  explore_first:
    name: 'explore_first'
    marker: '8'
  active_explorer:
    name: 'active_explorer'
    marker: '1'
  separate_classifiers:
    name: 'separate_classifiers'
    marker: 'v'
  softmax_explorer:
    name: 'softmax_explorer'
    marker: 'o'
  random_policy:
    name: 'random_policy'
    color: olive
  