train_episodes: 1
retrain_episodes: 20
test_episodes: 1
num_features: 8
window_len: 5
jiffies_per_state: 5
num_fields_kernel: 11
steps_per_episode: 10
knowledge_percentage: 50
delta: 0.5
lr: 1e-3
step_wait_seconds: 0.5
num_actions: 5